// Shared curriculum data accessible from both client and server

export const PROGRAM_WEEKS = [
  {
    weekNumber: 1,
    title: "Preflop Foundation",
    description: "Master opening ranges and blind defense",
    days: [
      {
        dayNumber: 1,
        label: "Opening Ranges",
        description: "Learn standard opening ranges from each position",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 2,
        label: "3-bet / 4-bet",
        description: "Study 3-bet and 4-bet strategies",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 3,
        label: "Blind Defense",
        description: "Master defending blinds vs raises",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 4,
        label: "Range Review",
        description: "Review and consolidate opening ranges",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 5,
        label: "Solver Drills",
        description: "Run solver drills on key positions",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 6,
        label: "Hand Review",
        description: "Review hands from recent sessions",
        drills: [{ tool: "Hand Tracker" }],
      },
      {
        dayNumber: 7,
        label: "Light Review",
        description: "Light review day - watch content or review notes",
        drills: [{ tool: "Content" }],
      },
    ],
  },
  {
    weekNumber: 2,
    title: "Postflop Fundamentals",
    description: "Master flop, turn, and river play",
    days: [
      {
        dayNumber: 1,
        label: "Flop C-Bets",
        description: "Study continuation betting on the flop",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 2,
        label: "Flop Checks",
        description: "Learn when and how to check the flop",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 3,
        label: "Turn Play",
        description: "Master turn strategy and decisions",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 4,
        label: "River Value",
        description: "Learn river value betting and bluffing",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 5,
        label: "Solver Drills",
        description: "Run solver drills on postflop scenarios",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 6,
        label: "Hand Review",
        description: "Review hands from recent sessions",
        drills: [{ tool: "Hand Tracker" }],
      },
      {
        dayNumber: 7,
        label: "Light Review",
        description: "Light review day - watch content or review notes",
        drills: [{ tool: "Content" }],
      },
    ],
  },
  {
    weekNumber: 3,
    title: "3-Bet Pots IP",
    description: "Master 3-bet pot play in position",
    days: [
      {
        dayNumber: 1,
        label: "3-Bet Ranges",
        description: "Study 3-bet ranges from each position",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 2,
        label: "IP Flops",
        description: "Master in-position flop play in 3-bet pots",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 3,
        label: "IP Turns",
        description: "Study turn play in 3-bet pots",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 4,
        label: "IP Rivers",
        description: "Learn river strategy in 3-bet pots",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 5,
        label: "Solver Drills",
        description: "Run solver drills on 3-bet pot scenarios",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 6,
        label: "Hand Review",
        description: "Review hands from recent sessions",
        drills: [{ tool: "Hand Tracker" }],
      },
      {
        dayNumber: 7,
        label: "Light Review",
        description: "Light review day - watch content or review notes",
        drills: [{ tool: "Content" }],
      },
    ],
  },
  {
    weekNumber: 4,
    title: "3-Bet Pots OOP",
    description: "Master 3-bet pot play out of position",
    days: [
      {
        dayNumber: 1,
        label: "OOP Defense",
        description: "Study defending 3-bets out of position",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 2,
        label: "OOP Flops",
        description: "Master out-of-position flop play",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 3,
        label: "OOP Turns",
        description: "Study turn play out of position",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 4,
        label: "OOP Rivers",
        description: "Learn river strategy out of position",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 5,
        label: "Solver Drills",
        description: "Run solver drills on OOP scenarios",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 6,
        label: "Hand Review",
        description: "Review hands from recent sessions",
        drills: [{ tool: "Hand Tracker" }],
      },
      {
        dayNumber: 7,
        label: "Light Review",
        description: "Light review day - watch content or review notes",
        drills: [{ tool: "Content" }],
      },
    ],
  },
  {
    weekNumber: 5,
    title: "Turn Barreling",
    description: "Master turn barreling and delayed c-bets",
    days: [
      {
        dayNumber: 1,
        label: "Turn Barrels",
        description: "Study turn barreling strategies",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 2,
        label: "Delayed C-Bets",
        description: "Learn delayed continuation betting",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 3,
        label: "Turn Checks",
        description: "Master when to check the turn",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 4,
        label: "Turn Raises",
        description: "Study turn raising strategies",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 5,
        label: "Solver Drills",
        description: "Run solver drills on turn scenarios",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 6,
        label: "Hand Review",
        description: "Review hands from recent sessions",
        drills: [{ tool: "Hand Tracker" }],
      },
      {
        dayNumber: 7,
        label: "Light Review",
        description: "Light review day - watch content or review notes",
        drills: [{ tool: "Content" }],
      },
    ],
  },
  {
    weekNumber: 6,
    title: "River Value & Bluff",
    description: "Master river value betting and bluffing",
    days: [
      {
        dayNumber: 1,
        label: "River Value",
        description: "Study river value betting",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 2,
        label: "River Bluffs",
        description: "Learn river bluffing strategies",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 3,
        label: "River Checks",
        description: "Master when to check the river",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 4,
        label: "River Raises",
        description: "Study river raising strategies",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 5,
        label: "Solver Drills",
        description: "Run solver drills on river scenarios",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 6,
        label: "Hand Review",
        description: "Review hands from recent sessions",
        drills: [{ tool: "Hand Tracker" }],
      },
      {
        dayNumber: 7,
        label: "Light Review",
        description: "Light review day - watch content or review notes",
        drills: [{ tool: "Content" }],
      },
    ],
  },
  {
    weekNumber: 7,
    title: "Triple Barrels",
    description: "Master triple barrel strategies",
    days: [
      {
        dayNumber: 1,
        label: "Triple Barrel Ranges",
        description: "Study triple barrel range construction",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 2,
        label: "Flop to Turn",
        description: "Master flop to turn barreling",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 3,
        label: "Turn to River",
        description: "Study turn to river barreling",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 4,
        label: "Defense",
        description: "Learn defending against triple barrels",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 5,
        label: "Solver Drills",
        description: "Run solver drills on barrel scenarios",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 6,
        label: "Hand Review",
        description: "Review hands from recent sessions",
        drills: [{ tool: "Hand Tracker" }],
      },
      {
        dayNumber: 7,
        label: "Light Review",
        description: "Light review day - watch content or review notes",
        drills: [{ tool: "Content" }],
      },
    ],
  },
  {
    weekNumber: 8,
    title: "Bubble ICM",
    description: "Master bubble play and ICM calculations",
    days: [
      {
        dayNumber: 1,
        label: "ICM Basics",
        description: "Learn ICM calculation fundamentals",
        drills: [{ tool: "ICM Trainer" }],
      },
      {
        dayNumber: 2,
        label: "Bubble Ranges",
        description: "Study bubble play ranges",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 3,
        label: "Chip Leader Play",
        description: "Master chip leader bubble strategy",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 4,
        label: "Short Stack Play",
        description: "Learn short stack bubble strategy",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 5,
        label: "Solver Drills",
        description: "Run solver drills on bubble scenarios",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 6,
        label: "Hand Review",
        description: "Review hands from recent sessions",
        drills: [{ tool: "Hand Tracker" }],
      },
      {
        dayNumber: 7,
        label: "Light Review",
        description: "Light review day - watch content or review notes",
        drills: [{ tool: "Content" }],
      },
    ],
  },
  {
    weekNumber: 9,
    title: "Final Table Play",
    description: "Master final table strategies",
    days: [
      {
        dayNumber: 1,
        label: "FT Ranges",
        description: "Study final table opening ranges",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 2,
        label: "FT Dynamics",
        description: "Learn final table dynamics and adjustments",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 3,
        label: "Heads Up Play",
        description: "Master heads up strategy",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 4,
        label: "3-Way Play",
        description: "Study 3-way final table play",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 5,
        label: "Solver Drills",
        description: "Run solver drills on FT scenarios",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 6,
        label: "Hand Review",
        description: "Review hands from recent sessions",
        drills: [{ tool: "Hand Tracker" }],
      },
      {
        dayNumber: 7,
        label: "Light Review",
        description: "Light review day - watch content or review notes",
        drills: [{ tool: "Content" }],
      },
    ],
  },
  {
    weekNumber: 10,
    title: "Live Exploits",
    description: "Master exploitative live play",
    days: [
      {
        dayNumber: 1,
        label: "Live Reads",
        description: "Learn live player reading techniques",
        drills: [{ tool: "Live Poker" }],
      },
      {
        dayNumber: 2,
        label: "Exploits",
        description: "Study exploitative strategies",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 3,
        label: "Table Image",
        description: "Master table image management",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 4,
        label: "Adjustments",
        description: "Learn dynamic adjustments",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 5,
        label: "Solver Drills",
        description: "Run solver drills on exploit scenarios",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 6,
        label: "Hand Review",
        description: "Review hands from recent sessions",
        drills: [{ tool: "Hand Tracker" }],
      },
      {
        dayNumber: 7,
        label: "Light Review",
        description: "Light review day - watch content or review notes",
        drills: [{ tool: "Content" }],
      },
    ],
  },
  {
    weekNumber: 11,
    title: "Advanced Concepts",
    description: "Master advanced poker concepts",
    days: [
      {
        dayNumber: 1,
        label: "Equity Concepts",
        description: "Study advanced equity calculations",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 2,
        label: "Blockers",
        description: "Learn blocker effects and strategy",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 3,
        label: "Polarization",
        description: "Master polarized betting strategies",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 4,
        label: "Balancing",
        description: "Learn balanced play and mixing",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 5,
        label: "Solver Drills",
        description: "Run solver drills on advanced scenarios",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 6,
        label: "Hand Review",
        description: "Review hands from recent sessions",
        drills: [{ tool: "Hand Tracker" }],
      },
      {
        dayNumber: 7,
        label: "Light Review",
        description: "Light review day - watch content or review notes",
        drills: [{ tool: "Content" }],
      },
    ],
  },
  {
    weekNumber: 12,
    title: "Consolidation",
    description: "Consolidate and review all concepts",
    days: [
      {
        dayNumber: 1,
        label: "Preflop Review",
        description: "Comprehensive preflop strategy review",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 2,
        label: "Postflop Review",
        description: "Comprehensive postflop strategy review",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 3,
        label: "Tournament Review",
        description: "Review tournament-specific strategies",
        drills: [{ tool: "Preflop+" }],
      },
      {
        dayNumber: 4,
        label: "Live Review",
        description: "Review live exploitative strategies",
        drills: [{ tool: "Live Poker" }],
      },
      {
        dayNumber: 5,
        label: "Playbook Building",
        description: "Build personal poker playbook",
        drills: [{ tool: "Hand Tracker" }],
      },
      {
        dayNumber: 6,
        label: "Leak Analysis",
        description: "Analyze and address personal leaks",
        drills: [{ tool: "GTO Wizard" }],
      },
      {
        dayNumber: 7,
        label: "Light Review",
        description: "Light review day - watch content or review notes",
        drills: [{ tool: "Content" }],
      },
    ],
  },
];
