// Expanded curriculum for Weeks 5-12 with complete drill specifications
// This file contains detailed drills for all remaining weeks

import type { StudyProgramWeek } from "./curriculumConfig";

export const expandedWeeks: StudyProgramWeek[] = [
  // WEEK 5: 3-Bet Pots In Position
  {
    weekIndex: 4,
    weekNumber: 5,
    themeCode: "3BET_IP",
    themeTitle: "3-Bet Pots In Position",
    themeDescription: "Master in-position play in 3-bet pots.",
    days: [
      {
        dayOfWeek: 1,
        planSlot: "DAY1_3BET_IP_RANGE",
        studyType: "RANGE_TRAINING",
        focusTitle: "3-Bet IP Ranges",
        focusDescription: "Build and drill 3-bet IP ranges from BTN/CO vs BB 3-bets",
        drills: [
          {
            drillId: "W5D1_3BET_IP_RANGES",
            title: "3-Bet IP Range Drills",
            primaryTool: "Preflop+",
            tools: ["Preflop+", "GTO Wizard"],
            reps: "50 hands",
            instructions: "Drill 3-bet IP ranges from BTN vs BB 3-bet. Focus on value/bluff balance and bet sizing.",
            successMetric: "90%+ accuracy on range construction",
          },
        ],
      },
      {
        dayOfWeek: 2,
        planSlot: "DAY2_3BET_IP_REVIEW",
        studyType: "HAND_REVIEW",
        focusTitle: "3-Bet IP Hand Review",
        focusDescription: "Review hands from 3-bet pots you played in position",
        drills: [
          {
            drillId: "W5D2_3BET_IP_HANDS",
            title: "3-Bet IP Hand Analysis",
            primaryTool: "Hand History Review",
            tools: ["Solver", "PioSOLVER"],
            reps: "10 hands",
            instructions: "Review 10 hands from 3-bet pots where you were IP. Compare decisions to solver outputs.",
            successMetric: "Identify 3+ exploitable patterns",
          },
        ],
      },
      {
        dayOfWeek: 3,
        planSlot: "DAY3_3BET_IP_ICM",
        studyType: "ICM",
        focusTitle: "ICM in 3-Bet Pots IP",
        focusDescription: "Study ICM adjustments for 3-bet pot play in position",
        drills: [
          {
            drillId: "W5D3_ICM_3BET_IP",
            title: "ICM Adjustments for 3-Bet Pots IP",
            primaryTool: "ICM Calculator",
            tools: ["ICM Calculator", "Tournament Poker Edge"],
            reps: "20 scenarios",
            instructions: "Study how ICM affects 3-bet IP ranges at different stack depths and chip positions.",
            successMetric: "Understand 3 key ICM adjustments",
          },
        ],
      },
      {
        dayOfWeek: 4,
        planSlot: "DAY4_3BET_IP_EXPLOIT",
        studyType: "EXPLOIT_LAB",
        focusTitle: "Exploiting 3-Bet IP Ranges",
        focusDescription: "Find and exploit opponent tendencies in 3-bet pots when in position",
        drills: [
          {
            drillId: "W5D4_EXPLOIT_3BET_IP",
            title: "Opponent Exploitation Drills",
            primaryTool: "Solver",
            tools: ["PioSOLVER", "Monker Poker"],
            reps: "15 exploits",
            instructions: "Identify 3-bet IP opponent tendencies (over-folding, over-calling, over-betting) and develop counter-strategies.",
            successMetric: "Create 3 exploitative adjustments",
          },
        ],
      },
      {
        dayOfWeek: 5,
        planSlot: "DAY5_3BET_IP_DEEP",
        studyType: "DEEP_DIVE",
        focusTitle: "Deep Dive: 3-Bet Pot IP Strategy",
        focusDescription: "In-depth study of 3-bet pot dynamics and strategy in position",
        drills: [
          {
            drillId: "W5D5_DEEP_3BET_IP",
            title: "3-Bet Pot IP Deep Dive",
            primaryTool: "PioSOLVER",
            tools: ["PioSOLVER", "YouTube"],
            reps: "2-3 hours",
            instructions: "Deep dive into 3-bet IP strategy. Study multi-street lines, c-bet frequencies, and turn play.",
            successMetric: "Master multi-street 3-bet IP strategy",
          },
        ],
      },
      {
        dayOfWeek: 6,
        planSlot: "DAY6_3BET_IP_MENTAL",
        studyType: "MENTAL_GAME",
        focusTitle: "Mental Game: 3-Bet Pots IP",
        focusDescription: "Manage variance and emotions in 3-bet pots when in position",
        drills: [
          {
            drillId: "W5D6_MENTAL_3BET_IP",
            title: "Variance Management in 3-Bet Pots",
            primaryTool: "Reflection",
            reps: "30 minutes",
            instructions: "Journal about mental challenges in 3-bet pots. Practice commitment to optimal lines despite variance.",
            successMetric: "Complete mental game reflection",
          },
        ],
      },
      {
        dayOfWeek: 7,
        planSlot: "DAY7_3BET_IP_LIGHT",
        studyType: "LIGHT_REVIEW",
        focusTitle: "Light Review: Week 5",
        focusDescription: "Review and consolidate week's learnings",
        drills: [
          {
            drillId: "W5D7_LIGHT_REVIEW",
            title: "Weekly Review",
            primaryTool: "Notebook",
            reps: "30 minutes",
            instructions: "Review notes from the week. Identify key takeaways for 3-bet IP play. Create action items.",
            successMetric: "Document 5 key learnings",
          },
        ],
      },
    ],
  },

  // WEEK 6: 3-Bet Pots OOP
  {
    weekIndex: 5,
    weekNumber: 6,
    themeCode: "3BET_OOP",
    themeTitle: "3-Bet Pots OOP",
    themeDescription: "Master out-of-position play in 3-bet pots.",
    days: [
      {
        dayOfWeek: 1,
        planSlot: "DAY1_3BET_OOP_RANGE",
        studyType: "RANGE_TRAINING",
        focusTitle: "3-Bet OOP Ranges",
        focusDescription: "Build and drill 3-bet OOP ranges from BB vs BTN/CO 3-bets",
        drills: [
          {
            drillId: "W6D1_3BET_OOP",
            title: "3-Bet OOP Range Drills",
            primaryTool: "Preflop+",
            tools: ["Preflop+", "GTO Wizard"],
            reps: "50 hands",
            instructions: "Drill 3-bet OOP ranges from BB vs BTN/CO 3-bets. Focus on check-calling ranges and aggression.",
            successMetric: "90%+ accuracy on OOP range construction",
          },
        ],
      },
      {
        dayOfWeek: 2,
        planSlot: "DAY2_3BET_OOP_REVIEW",
        studyType: "HAND_REVIEW",
        focusTitle: "3-Bet OOP Hand Review",
        focusDescription: "Review hands from 3-bet pots you played out of position",
        drills: [
          {
            drillId: "W6D2_3BET_OOP_HANDS",
            title: "3-Bet OOP Hand Analysis",
            primaryTool: "Hand History Review",
            tools: ["Solver", "PioSOLVER"],
            reps: "10 hands",
            instructions: "Review 10 hands from 3-bet pots where you were OOP. Analyze check-calling vs check-raising decisions.",
            successMetric: "Identify 3+ OOP mistakes",
          },
        ],
      },
      {
        dayOfWeek: 3,
        planSlot: "DAY3_3BET_OOP_ICM",
        studyType: "ICM",
        focusTitle: "ICM OOP Adjustments",
        focusDescription: "Study ICM adjustments for OOP 3-bet pots",
        drills: [
          {
            drillId: "W6D3_ICM_3BET_OOP",
            title: "ICM Adjustments OOP",
            primaryTool: "ICM Calculator",
            tools: ["ICM Calculator", "Tournament Poker Edge"],
            reps: "20 scenarios",
            instructions: "Study how ICM affects 3-bet OOP ranges. Focus on short-stack adjustments and bubble play.",
            successMetric: "Understand 3 key OOP ICM adjustments",
          },
        ],
      },
      {
        dayOfWeek: 4,
        planSlot: "DAY4_3BET_OOP_EXPLOIT",
        studyType: "EXPLOIT_LAB",
        focusTitle: "Exploiting 3-Bet OOP",
        focusDescription: "Find and exploit opponent tendencies in OOP 3-bet pots",
        drills: [
          {
            drillId: "W6D4_EXPLOIT_3BET_OOP",
            title: "OOP Exploitation Drills",
            primaryTool: "Solver",
            tools: ["PioSOLVER", "Monker Poker"],
            reps: "15 exploits",
            instructions: "Identify 3-bet OOP opponent tendencies and develop counter-strategies. Focus on aggression adjustments.",
            successMetric: "Create 3 OOP exploitative adjustments",
          },
        ],
      },
      {
        dayOfWeek: 5,
        planSlot: "DAY5_3BET_OOP_DEEP",
        studyType: "DEEP_DIVE",
        focusTitle: "Deep Dive: OOP 3-Bet Strategy",
        focusDescription: "In-depth study of OOP 3-bet dynamics",
        drills: [
          {
            drillId: "W6D5_DEEP_3BET_OOP",
            title: "OOP 3-Bet Deep Dive",
            primaryTool: "PioSOLVER",
            tools: ["PioSOLVER", "YouTube"],
            reps: "2-3 hours",
            instructions: "Deep dive into OOP 3-bet strategy. Study check-calling ranges, check-raising, and multi-street lines.",
            successMetric: "Master OOP multi-street strategy",
          },
        ],
      },
      {
        dayOfWeek: 6,
        planSlot: "DAY6_3BET_OOP_MENTAL",
        studyType: "MENTAL_GAME",
        focusTitle: "Mental Game: OOP Play",
        focusDescription: "Manage complexity and emotions in OOP situations",
        drills: [
          {
            drillId: "W6D6_MENTAL_3BET_OOP",
            title: "OOP Mental Resilience",
            primaryTool: "Reflection",
            reps: "30 minutes",
            instructions: "Journal about mental challenges in OOP 3-bet pots. Practice decision-making under pressure.",
            successMetric: "Complete mental game reflection",
          },
        ],
      },
      {
        dayOfWeek: 7,
        planSlot: "DAY7_3BET_OOP_LIGHT",
        studyType: "LIGHT_REVIEW",
        focusTitle: "Light Review: Week 6",
        focusDescription: "Review and consolidate week's learnings",
        drills: [
          {
            drillId: "W6D7_LIGHT_REVIEW",
            title: "Weekly Review",
            primaryTool: "Notebook",
            reps: "30 minutes",
            instructions: "Review notes from the week. Identify key takeaways for OOP 3-bet play. Create action items.",
            successMetric: "Document 5 key learnings",
          },
        ],
      },
    ],
  },

  // WEEK 7: Turn Barreling & Delayed C-Bets
  {
    weekIndex: 6,
    weekNumber: 7,
    themeCode: "TURN_BARRELS",
    themeTitle: "Turn Barreling & Delayed C-Bets",
    themeDescription: "Master turn aggression and delayed c-bet strategy.",
    days: [
      {
        dayOfWeek: 1,
        planSlot: "DAY1_TURN_RANGES",
        studyType: "RANGE_TRAINING",
        focusTitle: "Turn Barreling Ranges",
        focusDescription: "Build turn barreling ranges from different flop textures",
        drills: [
          {
            drillId: "W7D1_TURN_BARRELS",
            title: "Turn Barreling Drills",
            primaryTool: "PioSOLVER",
            tools: ["PioSOLVER", "Monker Poker"],
            reps: "40 hands",
            instructions: "Drill turn barreling ranges. Study value/bluff balance on different turn cards. Focus on bet sizing.",
            successMetric: "90%+ accuracy on turn barreling decisions",
          },
        ],
      },
      {
        dayOfWeek: 2,
        planSlot: "DAY2_TURN_REVIEW",
        studyType: "HAND_REVIEW",
        focusTitle: "Turn Play Hand Review",
        focusDescription: "Review hands with turn aggression and barreling",
        drills: [
          {
            drillId: "W7D2_TURN_HANDS",
            title: "Turn Play Analysis",
            primaryTool: "Hand History Review",
            tools: ["Solver", "PioSOLVER"],
            reps: "12 hands",
            instructions: "Review 12 hands focusing on turn decisions. Analyze barreling patterns and missed opportunities.",
            successMetric: "Identify 4+ turn strategy improvements",
          },
        ],
      },
      {
        dayOfWeek: 3,
        planSlot: "DAY3_TURN_ICM",
        studyType: "ICM",
        focusTitle: "Turn Play & ICM",
        focusDescription: "Study turn aggression adjustments based on ICM",
        drills: [
          {
            drillId: "W7D3_ICM_TURN",
            title: "ICM Turn Adjustments",
            primaryTool: "ICM Calculator",
            tools: ["ICM Calculator", "Tournament Poker Edge"],
            reps: "15 scenarios",
            instructions: "Study how ICM affects turn barreling ranges and aggression. Focus on bubble and final table.",
            successMetric: "Understand turn ICM adjustments",
          },
        ],
      },
      {
        dayOfWeek: 4,
        planSlot: "DAY4_TURN_EXPLOIT",
        studyType: "EXPLOIT_LAB",
        focusTitle: "Exploiting Turn Tendencies",
        focusDescription: "Find and exploit opponent turn play patterns",
        drills: [
          {
            drillId: "W7D4_EXPLOIT_TURN",
            title: "Turn Exploitation Drills",
            primaryTool: "Solver",
            tools: ["PioSOLVER", "Monker Poker"],
            reps: "12 exploits",
            instructions: "Identify opponent turn tendencies (check-folding, over-calling, under-barreling) and develop counters.",
            successMetric: "Create 3 turn exploitative adjustments",
          },
        ],
      },
      {
        dayOfWeek: 5,
        planSlot: "DAY5_TURN_DEEP",
        studyType: "DEEP_DIVE",
        focusTitle: "Deep Dive: Turn Strategy",
        focusDescription: "In-depth study of turn dynamics and aggression",
        drills: [
          {
            drillId: "W7D5_DEEP_TURN",
            title: "Turn Strategy Deep Dive",
            primaryTool: "PioSOLVER",
            tools: ["PioSOLVER", "YouTube"],
            reps: "2-3 hours",
            instructions: "Deep dive into turn strategy. Study delayed c-bets, multi-street lines, and river preparation.",
            successMetric: "Master turn aggression strategy",
          },
        ],
      },
      {
        dayOfWeek: 6,
        planSlot: "DAY6_TURN_MENTAL",
        studyType: "MENTAL_GAME",
        focusTitle: "Mental Game: Aggression",
        focusDescription: "Build confidence in aggressive turn play",
        drills: [
          {
            drillId: "W7D6_MENTAL_TURN",
            title: "Aggression Confidence",
            primaryTool: "Reflection",
            reps: "30 minutes",
            instructions: "Journal about confidence in turn aggression. Practice commitment to aggressive lines.",
            successMetric: "Complete mental game reflection",
          },
        ],
      },
      {
        dayOfWeek: 7,
        planSlot: "DAY7_TURN_LIGHT",
        studyType: "LIGHT_REVIEW",
        focusTitle: "Light Review: Week 7",
        focusDescription: "Review and consolidate week's learnings",
        drills: [
          {
            drillId: "W7D7_LIGHT_REVIEW",
            title: "Weekly Review",
            primaryTool: "Notebook",
            reps: "30 minutes",
            instructions: "Review notes from the week. Identify key turn strategy takeaways. Create action items.",
            successMetric: "Document 5 key learnings",
          },
        ],
      },
    ],
  },

  // WEEK 8: River Value/Bluff & Triple Barrels
  {
    weekIndex: 7,
    weekNumber: 8,
    themeCode: "RIVER_TRIPLE",
    themeTitle: "River Value/Bluff & Triple Barrels",
    themeDescription: "Master river strategy and aggressive multi-street lines.",
    days: [
      {
        dayOfWeek: 1,
        planSlot: "DAY1_RIVER_RANGES",
        studyType: "RANGE_TRAINING",
        focusTitle: "River Value/Bluff Ratios",
        focusDescription: "Build river value/bluff ranges from different run-outs",
        drills: [
          {
            drillId: "W8D1_RIVER_RANGES",
            title: "River Value/Bluff Drills",
            primaryTool: "PioSOLVER",
            tools: ["PioSOLVER", "Monker Poker"],
            reps: "45 hands",
            instructions: "Drill river value/bluff balance. Study bet sizing, frequency, and hand selection.",
            successMetric: "90%+ accuracy on river decisions",
          },
        ],
      },
      {
        dayOfWeek: 2,
        planSlot: "DAY2_RIVER_REVIEW",
        studyType: "HAND_REVIEW",
        focusTitle: "River Play Hand Review",
        focusDescription: "Review hands with river value and bluff decisions",
        drills: [
          {
            drillId: "W8D2_RIVER_HANDS",
            title: "River Play Analysis",
            primaryTool: "Hand History Review",
            tools: ["Solver", "PioSOLVER"],
            reps: "15 hands",
            instructions: "Review 15 hands focusing on river decisions. Analyze value/bluff balance and bet sizing.",
            successMetric: "Identify 5+ river strategy improvements",
          },
        ],
      },
      {
        dayOfWeek: 3,
        planSlot: "DAY3_RIVER_ICM",
        studyType: "ICM",
        focusTitle: "River Play & ICM",
        focusDescription: "Study river aggression adjustments based on ICM",
        drills: [
          {
            drillId: "W8D3_ICM_RIVER",
            title: "ICM River Adjustments",
            primaryTool: "ICM Calculator",
            tools: ["ICM Calculator", "Tournament Poker Edge"],
            reps: "18 scenarios",
            instructions: "Study how ICM affects river value/bluff ranges and bet sizing. Focus on final table.",
            successMetric: "Understand river ICM adjustments",
          },
        ],
      },
      {
        dayOfWeek: 4,
        planSlot: "DAY4_RIVER_EXPLOIT",
        studyType: "EXPLOIT_LAB",
        focusTitle: "Exploiting River Tendencies",
        focusDescription: "Find and exploit opponent river play patterns",
        drills: [
          {
            drillId: "W8D4_EXPLOIT_RIVER",
            title: "River Exploitation Drills",
            primaryTool: "Solver",
            tools: ["PioSOLVER", "Monker Poker"],
            reps: "14 exploits",
            instructions: "Identify opponent river tendencies (over-folding, over-calling, under-bluffing) and develop counters.",
            successMetric: "Create 4 river exploitative adjustments",
          },
        ],
      },
      {
        dayOfWeek: 5,
        planSlot: "DAY5_RIVER_DEEP",
        studyType: "DEEP_DIVE",
        focusTitle: "Deep Dive: River Strategy",
        focusDescription: "In-depth study of river dynamics and decision-making",
        drills: [
          {
            drillId: "W8D5_DEEP_RIVER",
            title: "River Strategy Deep Dive",
            primaryTool: "PioSOLVER",
            tools: ["PioSOLVER", "YouTube"],
            reps: "2-3 hours",
            instructions: "Deep dive into river strategy. Study triple barrels, value extraction, and bluff frequency.",
            successMetric: "Master river decision-making",
          },
        ],
      },
      {
        dayOfWeek: 6,
        planSlot: "DAY6_RIVER_MENTAL",
        studyType: "MENTAL_GAME",
        focusTitle: "Mental Game: River Decisions",
        focusDescription: "Build confidence in river value/bluff decisions",
        drills: [
          {
            drillId: "W8D6_MENTAL_RIVER",
            title: "River Decision Confidence",
            primaryTool: "Reflection",
            reps: "30 minutes",
            instructions: "Journal about river decision-making. Practice commitment to value/bluff lines.",
            successMetric: "Complete mental game reflection",
          },
        ],
      },
      {
        dayOfWeek: 7,
        planSlot: "DAY7_RIVER_LIGHT",
        studyType: "LIGHT_REVIEW",
        focusTitle: "Light Review: Week 8",
        focusDescription: "Review and consolidate week's learnings",
        drills: [
          {
            drillId: "W8D7_LIGHT_REVIEW",
            title: "Weekly Review",
            primaryTool: "Notebook",
            reps: "30 minutes",
            instructions: "Review notes from the week. Identify key river strategy takeaways. Create action items.",
            successMetric: "Document 5 key learnings",
          },
        ],
      },
    ],
  },

  // WEEK 9: Bubble ICM & Stack Dynamics
  {
    weekIndex: 8,
    weekNumber: 9,
    themeCode: "BUBBLE_ICM",
    themeTitle: "Bubble ICM & Stack Dynamics",
    themeDescription: "Master bubble play and ICM-adjusted strategy.",
    days: [
      {
        dayOfWeek: 1,
        planSlot: "DAY1_BUBBLE_ICM",
        studyType: "RANGE_TRAINING",
        focusTitle: "Bubble ICM Ranges",
        focusDescription: "Build bubble-adjusted ranges using ICM calculations",
        drills: [
          {
            drillId: "W9D1_BUBBLE_ICM",
            title: "Bubble ICM Range Drills",
            primaryTool: "ICM Calculator",
            tools: ["ICM Calculator", "ICMIZER", "Tournament Poker Edge"],
            reps: "50 scenarios",
            instructions: "Drill bubble ICM ranges at different stack depths. Study fold equity and chip EV.",
            successMetric: "90%+ accuracy on bubble ICM decisions",
          },
        ],
      },
      {
        dayOfWeek: 2,
        planSlot: "DAY2_BUBBLE_REVIEW",
        studyType: "HAND_REVIEW",
        focusTitle: "Bubble Play Hand Review",
        focusDescription: "Review hands from bubble play situations",
        drills: [
          {
            drillId: "W9D2_BUBBLE_HANDS",
            title: "Bubble Play Analysis",
            primaryTool: "Hand History Review",
            tools: ["ICM Calculator", "Solver"],
            reps: "10 hands",
            instructions: "Review 10 hands from bubble play. Analyze ICM-adjusted decisions and chip EV calculations.",
            successMetric: "Identify 3+ bubble strategy improvements",
          },
        ],
      },
      {
        dayOfWeek: 3,
        planSlot: "DAY3_BUBBLE_STACK",
        studyType: "ICM",
        focusTitle: "Stack Dynamics & Pressure",
        focusDescription: "Study how stack sizes affect strategy on the bubble",
        drills: [
          {
            drillId: "W9D3_STACK_DYNAMICS",
            title: "Stack Dynamics Study",
            primaryTool: "ICM Calculator",
            tools: ["ICM Calculator", "Tournament Poker Edge"],
            reps: "20 scenarios",
            instructions: "Study how different stack sizes (short, medium, big) affect bubble strategy. Focus on fold equity.",
            successMetric: "Understand stack dynamics",
          },
        ],
      },
      {
        dayOfWeek: 4,
        planSlot: "DAY4_BUBBLE_EXPLOIT",
        studyType: "EXPLOIT_LAB",
        focusTitle: "Exploiting Bubble Tendencies",
        focusDescription: "Find and exploit opponent bubble play patterns",
        drills: [
          {
            drillId: "W9D4_EXPLOIT_BUBBLE",
            title: "Bubble Exploitation Drills",
            primaryTool: "ICM Calculator",
            tools: ["ICM Calculator", "Solver"],
            reps: "12 exploits",
            instructions: "Identify opponent bubble tendencies (over-folding, over-pushing, ICM ignorance) and develop counters.",
            successMetric: "Create 3 bubble exploitative adjustments",
          },
        ],
      },
      {
        dayOfWeek: 5,
        planSlot: "DAY5_BUBBLE_DEEP",
        studyType: "DEEP_DIVE",
        focusTitle: "Deep Dive: Bubble Strategy",
        focusDescription: "In-depth study of bubble dynamics and ICM",
        drills: [
          {
            drillId: "W9D5_DEEP_BUBBLE",
            title: "Bubble Strategy Deep Dive",
            primaryTool: "ICM Calculator",
            tools: ["ICM Calculator", "YouTube"],
            reps: "2-3 hours",
            instructions: "Deep dive into bubble strategy. Study chip chop considerations, fold equity, and multi-way pots.",
            successMetric: "Master bubble ICM strategy",
          },
        ],
      },
      {
        dayOfWeek: 6,
        planSlot: "DAY6_BUBBLE_MENTAL",
        studyType: "MENTAL_GAME",
        focusTitle: "Mental Game: Bubble Pressure",
        focusDescription: "Manage emotions and pressure on the bubble",
        drills: [
          {
            drillId: "W9D6_MENTAL_BUBBLE",
            title: "Bubble Pressure Management",
            primaryTool: "Reflection",
            reps: "30 minutes",
            instructions: "Journal about bubble play emotions. Practice decision-making under bubble pressure.",
            successMetric: "Complete mental game reflection",
          },
        ],
      },
      {
        dayOfWeek: 7,
        planSlot: "DAY7_BUBBLE_LIGHT",
        studyType: "LIGHT_REVIEW",
        focusTitle: "Light Review: Week 9",
        focusDescription: "Review and consolidate week's learnings",
        drills: [
          {
            drillId: "W9D7_LIGHT_REVIEW",
            title: "Weekly Review",
            primaryTool: "Notebook",
            reps: "30 minutes",
            instructions: "Review notes from the week. Identify key bubble strategy takeaways. Create action items.",
            successMetric: "Document 5 key learnings",
          },
        ],
      },
    ],
  },

  // WEEK 10: Final Table Play & Chip Leader Strategy
  {
    weekIndex: 9,
    weekNumber: 10,
    themeCode: "FINAL_TABLE",
    themeTitle: "Final Table Play & Chip Leader Strategy",
    themeDescription: "Master final table dynamics and chip leader adjustments.",
    days: [
      {
        dayOfWeek: 1,
        planSlot: "DAY1_FT_RANGES",
        studyType: "RANGE_TRAINING",
        focusTitle: "Final Table Ranges",
        focusDescription: "Build final table opening and 3-bet ranges",
        drills: [
          {
            drillId: "W10D1_FT_RANGES",
            title: "Final Table Range Drills",
            primaryTool: "ICM Calculator",
            tools: ["ICM Calculator", "ICMIZER", "Preflop+"],
            reps: "50 scenarios",
            instructions: "Drill final table ranges at different positions and stack sizes. Study chip leader adjustments.",
            successMetric: "90%+ accuracy on final table decisions",
          },
        ],
      },
      {
        dayOfWeek: 2,
        planSlot: "DAY2_FT_REVIEW",
        studyType: "HAND_REVIEW",
        focusTitle: "Final Table Hand Review",
        focusDescription: "Review hands from final table play",
        drills: [
          {
            drillId: "W10D2_FT_HANDS",
            title: "Final Table Hand Analysis",
            primaryTool: "Hand History Review",
            tools: ["ICM Calculator", "Solver"],
            reps: "12 hands",
            instructions: "Review 12 hands from final table play. Analyze position, stack dynamics, and ICM adjustments.",
            successMetric: "Identify 4+ final table improvements",
          },
        ],
      },
      {
        dayOfWeek: 3,
        planSlot: "DAY3_FT_ICM",
        studyType: "ICM",
        focusTitle: "Final Table ICM",
        focusDescription: "Study ICM at final table with multiple stacks",
        drills: [
          {
            drillId: "W10D3_FT_ICM",
            title: "Final Table ICM Study",
            primaryTool: "ICM Calculator",
            tools: ["ICM Calculator", "Tournament Poker Edge"],
            reps: "25 scenarios",
            instructions: "Study final table ICM with 6-9 players. Focus on chip leader and short stack adjustments.",
            successMetric: "Understand final table ICM",
          },
        ],
      },
      {
        dayOfWeek: 4,
        planSlot: "DAY4_FT_EXPLOIT",
        studyType: "EXPLOIT_LAB",
        focusTitle: "Exploiting Final Table Tendencies",
        focusDescription: "Find and exploit opponent final table patterns",
        drills: [
          {
            drillId: "W10D4_EXPLOIT_FT",
            title: "Final Table Exploitation Drills",
            primaryTool: "ICM Calculator",
            tools: ["ICM Calculator", "Solver"],
            reps: "15 exploits",
            instructions: "Identify opponent final table tendencies (over-tightening, over-pushing, ICM ignorance) and develop counters.",
            successMetric: "Create 4 final table exploitative adjustments",
          },
        ],
      },
      {
        dayOfWeek: 5,
        planSlot: "DAY5_FT_DEEP",
        studyType: "DEEP_DIVE",
        focusTitle: "Deep Dive: Final Table Strategy",
        focusDescription: "In-depth study of final table dynamics",
        drills: [
          {
            drillId: "W10D5_DEEP_FT",
            title: "Final Table Strategy Deep Dive",
            primaryTool: "ICM Calculator",
            tools: ["ICM Calculator", "YouTube"],
            reps: "2-3 hours",
            instructions: "Deep dive into final table strategy. Study chip leader play, short stack shoves, and multi-way dynamics.",
            successMetric: "Master final table strategy",
          },
        ],
      },
      {
        dayOfWeek: 6,
        planSlot: "DAY6_FT_MENTAL",
        studyType: "MENTAL_GAME",
        focusTitle: "Mental Game: Final Table Pressure",
        focusDescription: "Manage emotions and focus on final table",
        drills: [
          {
            drillId: "W10D6_MENTAL_FT",
            title: "Final Table Mental Toughness",
            primaryTool: "Reflection",
            reps: "30 minutes",
            instructions: "Journal about final table emotions. Practice focus and decision-making under high pressure.",
            successMetric: "Complete mental game reflection",
          },
        ],
      },
      {
        dayOfWeek: 7,
        planSlot: "DAY7_FT_LIGHT",
        studyType: "LIGHT_REVIEW",
        focusTitle: "Light Review: Week 10",
        focusDescription: "Review and consolidate week's learnings",
        drills: [
          {
            drillId: "W10D7_LIGHT_REVIEW",
            title: "Weekly Review",
            primaryTool: "Notebook",
            reps: "30 minutes",
            instructions: "Review notes from the week. Identify key final table strategy takeaways. Create action items.",
            successMetric: "Document 5 key learnings",
          },
        ],
      },
    ],
  },

  // WEEK 11: Live Exploits & Opponent Adjustments
  {
    weekIndex: 10,
    weekNumber: 11,
    themeCode: "LIVE_EXPLOITS",
    themeTitle: "Live Exploits & Opponent Adjustments",
    themeDescription: "Master live poker exploitation and dynamic adjustments.",
    days: [
      {
        dayOfWeek: 1,
        planSlot: "DAY1_LIVE_READS",
        studyType: "RANGE_TRAINING",
        focusTitle: "Live Opponent Reads",
        focusDescription: "Study live tells and opponent categorization",
        drills: [
          {
            drillId: "W11D1_LIVE_READS",
            title: "Live Reads Training",
            primaryTool: "Observation",
            tools: ["Notebook", "YouTube"],
            reps: "50 observations",
            instructions: "Study live tells: betting patterns, timing, body language. Categorize opponents (tight, loose, aggressive, passive).",
            successMetric: "Identify 5+ reliable opponent tells",
          },
        ],
      },
      {
        dayOfWeek: 2,
        planSlot: "DAY2_LIVE_REVIEW",
        studyType: "HAND_REVIEW",
        focusTitle: "Live Hand Review",
        focusDescription: "Review hands from live play with opponent reads",
        drills: [
          {
            drillId: "W11D2_LIVE_HANDS",
            title: "Live Hand Analysis",
            primaryTool: "Hand History Review",
            tools: ["Notebook", "Video Review"],
            reps: "10 hands",
            instructions: "Review 10 hands from live play. Analyze opponent reads and how they affected decisions.",
            successMetric: "Identify 3+ exploitation opportunities",
          },
        ],
      },
      {
        dayOfWeek: 3,
        planSlot: "DAY3_LIVE_ADJUST",
        studyType: "ICM",
        focusTitle: "Live Adjustments",
        focusDescription: "Study dynamic adjustments based on opponent types",
        drills: [
          {
            drillId: "W11D3_LIVE_ADJUST",
            title: "Live Adjustment Study",
            primaryTool: "Notebook",
            tools: ["Solver", "Notebook"],
            reps: "20 scenarios",
            instructions: "Study adjustments for different opponent types. Create playbooks for tight, loose, aggressive, passive opponents.",
            successMetric: "Create 4 opponent-type playbooks",
          },
        ],
      },
      {
        dayOfWeek: 4,
        planSlot: "DAY4_LIVE_EXPLOIT",
        studyType: "EXPLOIT_LAB",
        focusTitle: "Live Exploitation Strategies",
        focusDescription: "Develop specific exploitation strategies for live opponents",
        drills: [
          {
            drillId: "W11D4_LIVE_EXPLOIT",
            title: "Live Exploitation Drills",
            primaryTool: "Notebook",
            tools: ["Solver", "Notebook"],
            reps: "15 strategies",
            instructions: "Develop specific exploitation strategies. Focus on position, stack depth, and opponent tendencies.",
            successMetric: "Create 5 specific exploitation strategies",
          },
        ],
      },
      {
        dayOfWeek: 5,
        planSlot: "DAY5_LIVE_DEEP",
        studyType: "DEEP_DIVE",
        focusTitle: "Deep Dive: Live Poker Strategy",
        focusDescription: "In-depth study of live poker dynamics",
        drills: [
          {
            drillId: "W11D5_DEEP_LIVE",
            title: "Live Poker Deep Dive",
            primaryTool: "Notebook",
            tools: ["YouTube", "Books"],
            reps: "2-3 hours",
            instructions: "Deep dive into live poker. Study game selection, table dynamics, and long-term adjustments.",
            successMetric: "Master live poker strategy",
          },
        ],
      },
      {
        dayOfWeek: 6,
        planSlot: "DAY6_LIVE_MENTAL",
        studyType: "MENTAL_GAME",
        focusTitle: "Mental Game: Live Poker",
        focusDescription: "Manage emotions and focus in live settings",
        drills: [
          {
            drillId: "W11D6_MENTAL_LIVE",
            title: "Live Mental Toughness",
            primaryTool: "Reflection",
            reps: "30 minutes",
            instructions: "Journal about live poker emotions. Practice focus and emotional control in live games.",
            successMetric: "Complete mental game reflection",
          },
        ],
      },
      {
        dayOfWeek: 7,
        planSlot: "DAY7_LIVE_LIGHT",
        studyType: "LIGHT_REVIEW",
        focusTitle: "Light Review: Week 11",
        focusDescription: "Review and consolidate week's learnings",
        drills: [
          {
            drillId: "W11D7_LIGHT_REVIEW",
            title: "Weekly Review",
            primaryTool: "Notebook",
            reps: "30 minutes",
            instructions: "Review notes from the week. Identify key live poker strategy takeaways. Create action items.",
            successMetric: "Document 5 key learnings",
          },
        ],
      },
    ],
  },

  // WEEK 12: Consolidation & Playbook Building
  {
    weekIndex: 11,
    weekNumber: 12,
    themeCode: "CONSOLIDATION",
    themeTitle: "Consolidation & Playbook Building",
    themeDescription: "Build written playbook from all prior weeks and review most frequent leaks.",
    days: [
      {
        dayOfWeek: 1,
        planSlot: "DAY1_PLAYBOOK_RANGES",
        studyType: "RANGE_TRAINING",
        focusTitle: "Playbook Range Summary",
        focusDescription: "Review and consolidate all ranges learned in the 12-week program",
        drills: [
          {
            drillId: "W12D1_PLAYBOOK_RANGES",
            title: "Range Consolidation",
            primaryTool: "Preflop+",
            tools: ["Preflop+", "GTO Wizard"],
            reps: "30 hands",
            instructions: "Review key ranges from all 11 weeks. Create a master range reference document.",
            successMetric: "Complete range consolidation document",
          },
        ],
      },
      {
        dayOfWeek: 2,
        planSlot: "DAY2_PLAYBOOK_REVIEW",
        studyType: "HAND_REVIEW",
        focusTitle: "Playbook Hand Review",
        focusDescription: "Review hands from all 11 weeks and identify patterns",
        drills: [
          {
            drillId: "W12D2_PLAYBOOK_HANDS",
            title: "Pattern Identification",
            primaryTool: "Hand History Review",
            tools: ["Solver", "Notebook"],
            reps: "20 hands",
            instructions: "Review 20 hands from throughout the program. Identify recurring mistakes and patterns.",
            successMetric: "Identify 5+ recurring patterns",
          },
        ],
      },
      {
        dayOfWeek: 3,
        planSlot: "DAY3_PLAYBOOK_ICM",
        studyType: "ICM",
        focusTitle: "ICM Playbook Summary",
        focusDescription: "Consolidate ICM knowledge from all weeks",
        drills: [
          {
            drillId: "W12D3_PLAYBOOK_ICM",
            title: "ICM Consolidation",
            primaryTool: "ICM Calculator",
            tools: ["ICM Calculator", "Notebook"],
            reps: "15 scenarios",
            instructions: "Review ICM concepts from all weeks. Create ICM decision tree for different situations.",
            successMetric: "Create ICM decision tree",
          },
        ],
      },
      {
        dayOfWeek: 4,
        planSlot: "DAY4_PLAYBOOK_EXPLOIT",
        studyType: "EXPLOIT_LAB",
        focusTitle: "Exploitation Playbook",
        focusDescription: "Consolidate exploitation strategies from all weeks",
        drills: [
          {
            drillId: "W12D4_PLAYBOOK_EXPLOIT",
            title: "Exploitation Consolidation",
            primaryTool: "Notebook",
            tools: ["Solver", "Notebook"],
            reps: "10 strategies",
            instructions: "Review exploitation strategies from all weeks. Create a master exploitation playbook.",
            successMetric: "Create exploitation playbook",
          },
        ],
      },
      {
        dayOfWeek: 5,
        planSlot: "DAY5_PLAYBOOK_DEEP",
        studyType: "DEEP_DIVE",
        focusTitle: "Deep Dive: Program Review",
        focusDescription: "Comprehensive review of the entire 12-week program",
        drills: [
          {
            drillId: "W12D5_DEEP_PLAYBOOK",
            title: "12-Week Program Review",
            primaryTool: "Notebook",
            tools: ["Notebook", "Video"],
            reps: "2-3 hours",
            instructions: "Review entire 12-week program. Identify biggest improvements and remaining weaknesses.",
            successMetric: "Complete program review",
          },
        ],
      },
      {
        dayOfWeek: 6,
        planSlot: "DAY6_PLAYBOOK_MENTAL",
        studyType: "MENTAL_GAME",
        focusTitle: "Mental Game: Program Reflection",
        focusDescription: "Reflect on mental game improvements throughout the program",
        drills: [
          {
            drillId: "W12D6_MENTAL_PLAYBOOK",
            title: "Mental Game Reflection",
            primaryTool: "Reflection",
            reps: "30 minutes",
            instructions: "Journal about mental game improvements. Identify areas for continued growth.",
            successMetric: "Complete mental game reflection",
          },
        ],
      },
      {
        dayOfWeek: 7,
        planSlot: "DAY7_PLAYBOOK_LIGHT",
        studyType: "LIGHT_REVIEW",
        focusTitle: "Program Completion",
        focusDescription: "Celebrate completion and plan next steps",
        drills: [
          {
            drillId: "W12D7_PROGRAM_COMPLETE",
            title: "Program Completion",
            primaryTool: "Notebook",
            reps: "30 minutes",
            instructions: "Celebrate completing the 12-week program. Plan next steps for continued improvement.",
            successMetric: "Create 90-day improvement plan",
          },
        ],
      },
    ],
  },
];
